module.exports.descriptors = [
    'Helping',
    'Supporting',
    'Teaching',
    'Paying for',
    'Training',
    'Accompanying',
    'Guiding',
    'Keeping company of',
    'Raising money for',
    'Entertaining',
    'Coaching',
    'Teaching',
    'Fundraising for',
    'Helping',
    'cleaning for',
    'Doing groceries for ',
    'Collecting money for',
    'Cleaning for'
]

module.exports.places = [
    'poor people',
    'Ethiopian',
    'Ukranian kids',
    'eldery',
    'a public school ',
    'dogs',
    'abandoned children',
    'disabled people',
    'disabled children',
    'sick children',
    'abandoned animals',
    'injured animals',
    'disabled elderly',
    'oliem',
    'children with learning disabilities',
    'lonely soldiers',
    'soldiers',
    'people with dementia',
    'orphans',
    'children with autism',
    'disabled elderly'
]
